on:
  push

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: Install Databricks CLI
        uses: databricks/setup-cli@main
        
      - name: Remote list Prod Repo
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          databricks repos list

      - name: Remote update Prod Repo
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          databricks repos list
          databricks repos update "/Workspace/Users/bitxuji@gmail.com/GitHub Folders/Prod/databricks-git-folders-1" --branch main
